---
name: "Flipkart app image build and deploy"


on:
  push:
    branches:
      - master
      - testing
      - production
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      packer_version: "1.9.4"

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Installing Packer"
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.packer_version }}

      - name: "Packer init by setting up working directory"
        run: packer init .
        working-directory: ./packer/

      - name: "Packer validate"
        run: packer validate .
        working-directory: ./packer/

      - name: "Packer build"
        run: packer build ./packer
